### ISSUE TITLE
GCC first pass (chapter 5.5) - Out of memory

### ISSUE THREAD

**Issue by EvilFreelancer** [reinterpretcat/lfs#1]
Hello @reinterpretcat! I'm happy to create the first issue here :)
I'm having a problem with the LFS build phase, in particular with chapter 5.5.

A few minutes after script started working on this chapter (at the compilation stage of mpfr), I see a message saying that the container does not have enough memory (a lot of memory allocation errors), I have 16GB of RAM and the same size of the swap partition (video montage my hobbie).

What I just did not try... first I've changed the build directory from /tmp to /build, then I've set the "ulimit" (in bash and docker-compote.yml), yeah I've also rewriten some things to docker-compose (especially for mounting external directories and storing as little data as possible in the container).

https://github.com/EvilFreelancer/lfs/blob/master/docker-compose.yml

Funniest thing is that if I take only scripts and configure a normal virtual machine (virtualbox), then GCC compilation complete without problems.

    ~ $ docker -v
    Docker version 18.02.0-ce, build fc4de44

    ~ $ docker-compose -v
    docker-compose version 1.17.0, build ac53b73

    ~ $ free -h
                  total        used        free      shared  buff/cache   available
    Mem:            15G        7,8G        271M        300M        7,5G        7,4G
    Swap:           15G         37M         15G

According to my observations, the docker does not know how to manage memory, perhaps this is due to the fact that I installed an unstable binary package (18.02)

**Comment by reinterpretcat** [comment]
Hi EvilFreelancer,

Hard to say what is the reason of the issue in your case.. I was running scripts on my environment with less physical memory (12Gb Ubuntu 17.10 and 10Gb Ubuntu 16.04) without OoM exceptions.

To debug scripts, I used to create an image from stopped container which exited due to an issue. Then I could start a new container with modified entrypoint running sh shell. 

I guess this approach might help you to understand how to fix the issue on your environment without rerunning all scripts again.

**Comment by EvilFreelancer** [comment]
Yeah, I've found what issue in memory after few reruns, fast solution to make this:

    cd /mnt/lfs/sources
    sh /mnt/lfs/scripts/prepare/5.5-make-gcc.sh

Maybe issue with new docker, what do you think? What version of your docker (probably my problem is here)?

**Comment by reinterpretcat** [comment]
On Ubuntu 16.04 I have:
`
Docker version 17.05.0-ce, build 89658be`

**Comment by EvilFreelancer** [comment]
Hello!
I've checked build process on 17.05 verions of Docker and seems I was right, bug with memory usage in 18 version. Maybe need to add some note about this into the readme file?

---

The second thing, almost all fine, but seems you forgot set absolute path of the /dev/loop2 device inside `scripts/image/2.create-ramdisk.sh` file:

   Start building bootable image..
   /tmp /mnt/lfs/sources
   Configuring syslinux..
   Creating ramdisk..
   800000+0 records in
   800000+0 records out
   819200000 bytes (819 MB) copied, 2.19472 s, 373 MB/s
   losetup: /dev/loop2: failed to set up loop device: No such file or directory

I'll send PR with this to you :)

**Comment by reinterpretcat** [comment]
thanks, PR will be great :)
