### ISSUE TITLE
Unable to build the LFS

### ISSUE THREAD

**Issue by chaitanyarahalkar** [reinterpretcat/lfs#11]
Hey,

docker rm lfs                                       && \
docker build --tag lfs:8.2 .                        && \
sudo docker run -it --privileged --name lfs lfs:8.2 && \
sudo docker cp lfs:/tmp/lfs.iso .

I ran this exact command on a Google Cloud VM with Docker. It creates multiple different images and doesn't generate the .iso as expected. Please look into this.

Thanks

**Comment by reinterpretcat** [comment]
Do you have any logs? There is not enough information.
Also please note that this is just a project to learn a bit how to build minimalistic linux environment, so if you have some troubles, you can research on your own and learn from it.

**Comment by fishcharlie** [comment]
@chaitanyarahalkar I'd check out my PR I just submitted (#15), which includes a lot of fixes for LFS 8.2. Let me know if you are still running into problems after trying that.

@reinterpretcat I think this issue can probably be closed due to inactivity and no reply from @chaitanyarahalkar.

**Comment by reinterpretcat** [comment]
Agree
