### ISSUE TITLE
LFS 8.4

### ISSUE THREAD

**Issue by fishcharlie** [reinterpretcat/lfs#12]
Linux From Scratch is now on version 8.4. Are there any plans to update this to support the latest version?

**Comment by M0E-lnx** [comment]
+1 on this

**Comment by reinterpretcat** [comment]
No, I don't have plans to update, however contributions are welcome..

**Comment by fishcharlie** [comment]
Due to the fact that there are no current plans to do this, I'm going to close this issue.
