### ISSUE TITLE
Full-featured operating system inside Docker

### ISSUE THREAD

**Issue by EvilFreelancer** [reinterpretcat/lfs#4]
Hello @reinterpretcat!
I've build small docker image from ISO which was generated by scripts, what you created.
https://hub.docker.com/r/evilfreelancer/lfs/
Details about "how to build" in description of  docker image. Size is too large (~450Mb), but for the purposes of learning this is not very important.

I will be happy with your wishes and suggestions 😄 Btw, if you have an account on the docker hub, I can add you as collaborator.

**Comment by reinterpretcat** [comment]
Hi @EvilFreelancer!

Thanks for feedback.
I also prepared iso which is attached as release artifact here: https://github.com/reinterpretcat/lfs/releases/tag/v8.1.0

I don't have yet account on docker hub, but I'm happy that the project is continued somehow :)

**Comment by EvilFreelancer** [comment]
Okay, cool! Btw https://discord.gg/JqdWH8q here the LFS almost official group in Discord, if want you may enjoy. Спасибо Вам, за Ваши труды :)

**Comment by reinterpretcat** [comment]
Да не за что ;)
