### ISSUE TITLE
losetup error!

### ISSUE THREAD

**Issue by mohmsslk** [reinterpretcat/lfs#6]
Hi,

I get teh following error: 

losetup: /tmp/ramdisk: failed to set up loop device: Device or resource busy

Any idea? and which command to continue the building, I dont want to start again.

Thank you

**Comment by reinterpretcat** [comment]
Hi,
Take a look at 
https://github.com/reinterpretcat/lfs/blob/master/scripts/image/2.create-ramdisk.sh

By default, loop device is set in Dockerfile using

ENV LOOP=/dev/loop0

Try to specify different index (e.g. loop1)

**Comment by mohmsslk** [comment]
Hi,

it works with ENV LOOP=/dev/loop1

Thank you
