### ISSUE TITLE
LFS 8.3: gawk-4.2.1 'make' no error,but 'make check' has 2 errors.

### ISSUE THREAD

**Issue by guoyanzhang0817** [reinterpretcat/lfs#9]
[lfs@archlinux gawk-4.2.1]$ make check
Making check in support
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/support'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/support'
Making check in .
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1'
make 'CFLAGS=-g -O2 -DNDEBUG' 'LDFLAGS=' check-local
make[2]: Entering directory '/mnt/lfs/sources/gawk-4.2.1'
make[2]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1'
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1'
Making check in extension
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/extension'
make[2]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/extension'
make[2]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/extension'
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/extension'
Making check in extras
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/extras'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/extras'
Making check in doc
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/doc'
Making check in awklib
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/awklib'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/awklib'
Making check in po
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/po'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/po'
Making check in test
make[1]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/test'

Any output from "cmp" is bad news, although some differences
in floating point values are probably benign -- in particular,
some systems may omit a leading zero and the floating point
precision may lead to slightly different output in a few cases.

Locale environment:
	LC_ALL="C" LANG="C"

======== Starting basic tests ========
addcomma
anchgsub
anchor
argarray
arrayind1
arrayind2
arrayind3
arrayparm
arrayprm2
arrayprm3
arrayref
arrymem1
arryref2
arryref3
arryref4
arryref5
arynasty
arynocls
aryprm1
aryprm2
aryprm3
aryprm4
aryprm5
aryprm6
aryprm7
aryprm8
aryprm9
arysubnm
aryunasgn
asgext
awkpath
back89
backgsub
badassign1
badbuild
callparam
childin
clobber
closebad
clsflnam
compare
compare2
concat1
concat2
concat3
concat4
concat5
convfmt
datanonl
defref
delargv
delarpm2
delarprm
delfunc
dfamb1
dfastress
dynlj
eofsplit
exit2
exitval1
exitval2
exitval3
fcall_exit
fcall_exit2
fldchg
fldchgnf
fldterm
fnamedat
fnarray
fnarray2
fnaryscl
fnasgnm
fnmisc
fordel
forref
forsimp
fsbs
fsnul1
fsrs
fsspcoln
fstabplus
funsemnl
funsmnam
funstack
getline
getline2
getline3
getline4
getline5
getlnbuf
getnr2tb
getnr2tm
gsubasgn
gsubtest
gsubtst2
gsubtst3
gsubtst4
gsubtst5
gsubtst6
gsubtst7
gsubtst8
hex
hex2
hsprint
inpref
inputred
intest
intprec
iobug1
leaddig
leadnl
litoct
longsub
longwrds
manglprm
math
membug1
memleak
messages
minusstr
mmap8k
nasty
nasty2
negexp
negrange
nested
nfldstr
nfloop
nfneg
nfset
nlfldsep
nlinstr
nlstrina
noeffect
nofile
nofmtch
noloop1
noloop2
nonl
noparms
nors
nulinsrc
nulrsend
numindex
numstr1
numsubstr
octsub
ofmt
ofmta
ofmtbig
ofmtfidl
ofmts
ofmtstrnum
ofs1
onlynl
opasnidx
opasnslf
paramasfunc1
paramasfunc2
paramdup
paramres
paramtyp
paramuninitglobal
parse1
parsefld
parseme
pcntplus
posix2008sub
prdupval
prec
printf0
printf1
printfchar
prmarscl
prmreuse
prt1eval
prtoeval
rand
randtest
range1
readbuf
rebrackloc
rebt8b1
rebuild
redfilnm
regeq
regexpbrack
regexpbrack2
regexprange
regrange
reindops
reparse
resplit
rri1
rs
rscompat
rsnul1nl
rsnulbig
rsnulbig2
rstest1
rstest2
rstest3
rstest4
rstest5
rswhite
scalar
sclforin
sclifin
setrec0
setrec1
sigpipe1
sortempty
sortglos
splitargv
splitarr
splitdef
splitvar
splitwht
status-close
strcat1
strnum1
strnum2
strtod
subamp
subback
subi18n
subsepnm
subslash
substr
swaplns
synerr1
synerr2
tradanch
tweakfld
uninit2
uninit3
uninit4
uninit5
uninitialized
unterm
uparrfs
uplus
wideidx
wideidx2
widesub
widesub2
widesub3
widesub4
wjposer1
zero2
zeroe0
zeroflag
======== Done with basic tests ========
======== Starting Unix tests ========
fflush
getlnhd
localenl
pid
pipeio1
pipeio2
poundbang
rtlen
rtlen01
space
strftlng
======== Done with Unix tests ========
======== Starting gawk extension tests ========
aadelete1
aadelete2
aarray1
aasort
aasorti
argtest
arraysort
backw
badargs
beginfile1
beginfile2
binmode1
charasbytes
colonwarn
clos1way
clos1way2
clos1way3
clos1way4
clos1way5
clos1way6
crlf
dbugeval
dbugeval2
dbugtypedre1
dbugtypedre2
delsub
devfd
devfd1
devfd2
dumpvars
errno
exit
fieldwdth
forcenum
fpat1
fpat2
fpat3
fpat4
fpat5
fpat6
fpatnull
fsfwfs
funlen
functab1
functab2
functab3
fwtest
fwtest2
fwtest3
fwtest4
fwtest5
fwtest6
fwtest7
fwtest8
genpot
gensub
gensub2
gensub3
getlndir
gnuops2
gnuops3
gnureops
gsubind
icasefs
icasers
id
igncdym
igncfs
ignrcas2
ignrcas4
ignrcase
incdupe
incdupe2
incdupe3
incdupe4
incdupe5
incdupe6
incdupe7
include
include2
indirectbuiltin
indirectcall
indirectcall2
intarray
isarrayunset
lint
lintexp
lintindex
lintint
lintlength
lintold
lintset
lintwarn
mixed1
mktime
manyfiles
match1
match2
match3
mbstr1
./mbstr1.ok _mbstr1 differ: char 1, line 1
make[1]: [Makefile:2405: mbstr1] Error 1 (ignored)
mbstr2
./mbstr2.ok _mbstr2 differ: char 6, line 2
make[1]: [Makefile:2411: mbstr2] Error 1 (ignored)
muldimposix
nastyparm
negtime
next
nondec
nondec2
nonfatal1
nonfatal2
nonfatal3
patsplit
posix
printfbad1
printfbad2
printfbad3
printfbad4
printhuge
procinfs
profile0
profile1
profile2
profile3
profile4
profile5
profile6
profile7
profile8
profile9
profile10
pty1
pty2
rebuf
regnul1
regnul2
regx8bit
reginttrad
reint
reint2
rsgetline
rsglstdin
rsstart1
rsstart2
rsstart3
rstest6
shadow
shadowbuiltin
sortfor
sortfor2
sortu
sourcesplit
split_after_fpat
splitarg4
strftime
strftfld
strtonum
strtonum1
switch2
symtab1
symtab2
symtab3
symtab4
symtab5
symtab6
symtab7
symtab8
symtab9
symtab10
typedregex1
typedregex2
typedregex3
typeof1
typeof2
typeof3
typeof4
typeof5
timeout
watchpoint1
gawk is not compiled to support the array debug tests
======== Done with gawk extension tests ========
======== Starting machine-specific tests ========
double1
double2
fmtspcl
intformat
======== Done with machine-specific tests ========
%%%%%%%%%% Inadequate locale support: skipping charset tests.
%%%%%%%%%% At least en_US.UTF-8, fr_FR.UTF-8, ru_RU.UTF-8 and ja_JP.UTF-8 are needed.
======== Starting shared library tests ========
make[2]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/test'
apiterm
filefuncs
fnmatch
fork
fork2
fts
functab4
getfile
inplace1
inplace2
inplace3
ordchr
ordchr2
readdir
readdir_test
readfile
readfile2
revout
revtwoway
rwarray
testext
time
make[2]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/test'
======== Done with shared library tests ========
======== Starting MPFR tests ========
MPFR tests not supported on this system
======== Done with MPFR tests ========
make[2]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/test'
2 TESTS FAILED
make[2]: *** [Makefile:4646: pass-fail] Error 1
make[2]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/test'
make[2]: Entering directory '/mnt/lfs/sources/gawk-4.2.1/test'
for i in _* ; \
do  \
	if [ "$i" != "_*" ]; then \
	echo ============== $i ============= ; \
	base=`echo $i | sed 's/^_//'` ; \
	if [ -r ${base}.ok ]; then \
	diff -c ${base}.ok $i ; \
	else \
	diff -c "."/${base}.ok  $i ; \
	fi ; \
	fi ; \
done | more
============== _mbstr1 =============
*** mbstr1.ok	Thu Dec 14 17:53:45 2017
--- _mbstr1	Sat Dec 15 06:35:00 2018
***************
*** 1,3 ****
- gawk: mbstr1.awk:2: warning: Invalid multibyte data detected. There may be a m
ismatch between your data and your locale.
  4
  1
--- 1,2 ----
============== _mbstr2 =============
*** mbstr2.ok	Thu Dec 14 17:53:45 2017
--- _mbstr2	Sat Dec 15 06:35:00 2018
***************
*** 1,5 ****
  2007
- gawk: mbstr2.awk:1: (FILENAME=- FNR=2) warning: Invalid multibyte data detecte
d. There may be a mismatch between your data and your locale.
  2007
  2007
  2007
--- 1,4 ----
make[2]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/test'
make[1]: *** [Makefile:1819: check] Error 1
make[1]: Leaving directory '/mnt/lfs/sources/gawk-4.2.1/test'
make: *** [Makefile:725: check-recursive] Error 1
[lfs@archlinux gawk-4.2.1]$

**Comment by reinterpretcat** [comment]
I don't know what is wrong here. I think you can try to ask question on LFS dedicated forums..

**Comment by guoyanzhang0817** [comment]
> I don't know what is wrong here. I think you can try to ask question on LFS dedicated forums..
sorry, can you give me a link about LFS dedicated forums?  I didn't find.

**Comment by reinterpretcat** [comment]
During development, I found some useful information here: https://www.linuxquestions.org/questions/linux-from-scratch-13/

Also check available options here: http://www.linuxfromscratch.org/support.html

In most cases, issue can be resolved starting from beginning precisely following all instructions.

**Comment by guoyanzhang0817** [comment]
> During development, I found some useful information here: https://www.linuxquestions.org/questions/linux-from-scratch-13/
> 
> Also check available options here: http://www.linuxfromscratch.org/support.html
> 
> In most cases, issue can be resolved starting from beginning precisely following all instructions.

thank you.
